apiVersion: v1alpha1
kind: UnattendedInstallConfig
installer:
  image: factory.talos.dev/metal-installer/4a0d65c669d46663f377e7161e50cfd570c401f26fd9e7bda34a0216b6f1922b:v1.14.0
provisioning:
  diskSelector:
    match: disk.dev_path == "/dev/vda"
  wipe: false
